### ISSUE TITLE
Find max_dist function?

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#4]
Any way we could write a function which would find the best value for `max_dist`? The user would have to specify a given model and then then a range of possible values for `max_dist` (e.g., 5 m to 20m). Then the function would test each one and find the one with the lowest RMSE? Would be cool because then we would know what is teh distance at which competition is felt. Of biological interest. 

Not 100% necessary, but would be a cool function to include in the package if possible.

**Comment by rudeboybert** [comment]
Mos def!

**Comment by rudeboybert** [comment]
punted
