### ISSUE TITLE
Lambda plotting function problem

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#41]
I really like the way you have that sentence at the top of the plot "Ex: Top row, second column = competitive effect of __ on __" but looks like it doesn't "play nice" with `sp_to_plot`. 
![README-unnamed-chunk-30-1](https://user-images.githubusercontent.com/20326594/94992115-b6abbf00-0555-11eb-8351-f52ee905f8ad.png)

**Comment by dallenmidd** [comment]
Your fix doesn't work 100%. The  issue is that is looks like the text is based on the ordering the user gives in `sp_to_plot`, but the ordering in the plot itself is alphabetical regardless of the order the user gave the species in. Here is an example
<img width="959" alt="Screen Shot 2020-10-10 at 5 02 20 PM" src="https://user-images.githubusercontent.com/20326594/95665043-aaf26680-0b1a-11eb-83c0-b991e43fbd9d.png">

**Comment by rudeboybert** [comment]
Ah, darn factors auto-sorting themselves. Fixed 
<img width="834" alt="Screen Shot 2020-10-14 at 7 43 01 AM" src="https://user-images.githubusercontent.com/4574203/95984243-e5952100-0df0-11eb-94a6-da2cbf245c17.png">
