### ISSUE TITLE
Make small example

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#43]
Make a minimal example (2 folds, 2 species) to give as an example for the whole workflow.

**Comment by dallenmidd** [comment]
`spatialBlock` is bricking my computer when I try and run it on my small example. Like totally freezes RStudio. Wonder if you could take a look. In the `small_example` branch look at `spatial_block_issue.R` . For me this runs all the way to 37, but then that command is the one that freeze me. To my mind `ex_growth_df` has the same structure as `bw_growth_df` and `scbi_growth_df` for which `spatialBlock` runs.

**Comment by rudeboybert** [comment]
Check out e830480b6ea96e881733a1a7ed1805954a13b3b7: we manually define an sf object of the CV grid
