### ISSUE TITLE
couple little things

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#6]
- Progress bar for `create_focal_vs_comp` it takes a little while
- Rename `fit_bayesain_model` to `fit_comp_model`? Is the importance of it that it is a model of competition or that it is bayesian? To me emphasizing competition seems more important, but I am not sure. 
- Same as above for `predict_bayesain_model`.

**Comment by rudeboybert** [comment]
Fixed in transition to `comp_bayes_lm` S3 class we defined in #51.

Punt on progress bar. Done is better than perfect
