### ISSUE TITLE
Allow for model selection between multiple competitive distances

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/forestecology#69]
Change [`run_cv()`](https://github.com/rudeboybert/forestecology/blob/master/R/model_functions.R#L256) to take vector argument of multiple `comp_dist` values and thus will involve different `focal_vs_comp` data frames

This should only be done for cross-validated RMSE values, as comparing non-cross-validated RMSE's based on overfit models is of little use.

**Comment by dallenmidd** [comment]
Wow you did that so quickly. Excited to see how it works out on the actual dataset.

**Comment by rudeboybert** [comment]
No longer going to program this is a function; rather just run `run_cv()` multiple times
