### ISSUE TITLE
Conspecific versus heterospecific competition

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#73]
To address the reviewer's critique that the model is not flexible enough and does not include applications of existing competition theory, we could add another option for `run_shuffle`. In this case the shuffle would not shuffle identity of competitors which share with the focal species. The idea being there is a special kind of competition with conspecifics (because they share your exact resource needs). The result is two lambda values, one for competition between conspecifics and one for competition between heterospecifics.

**Comment by rudeboybert** [comment]
Abandoned given that it wasn't addressed in review
