### ISSUE TITLE
Option for additional predictor variables

### ISSUE THREAD

**Issue by dallenmidd** [rudeboybert/forestecology#75]
R2 said: "It also lacks functionality to accommodate multiple census periods or variability between sites or a clear way to use the results to simulate forest stand dynamics over space and time. "

The last issue is ridiculous because then the model would need to have full demography (mortality, seed dispersal, and recruitment) which is way out of the scope of the intention). But the first two issues could be addressed if we gave the option of additional predictor variables on growth. They could be categorical or continuous. For example I think SCBI has a deer exclosure, there could be a categorical predictor for is the stem in the exclosure or not. For continuous it could be the elevation the stem is at or an estimate of the soil N where the stem is. For multiple censuses each transition (census 1 to 2 and then 2 to 3) for each stem could be modeled and census interval (1 to 2 or 2 to 3) could be the categorical predictor.

HEre is how it might work. Say individual *k* is in category *l* then your model would be:
<img width="361" alt="Screen Shot 2021-04-30 at 1 48 08 PM" src="https://user-images.githubusercontent.com/20326594/116733931-bde75e00-a9ba-11eb-902c-ccf2da0a5296.png">
Where *c_l* is the effect on growth of stems in category *l*

Or if the predictor was continuous and takes value *c_k* at individual *k*, then:
<img width="372" alt="Screen Shot 2021-04-30 at 1 49 59 PM" src="https://user-images.githubusercontent.com/20326594/116734099-fa1abe80-a9ba-11eb-8e50-7e4c73466022.png">
Where *a_c* is the effect of that continuous predictor on growth.

**Comment by rudeboybert** [comment]
Abandoned, given that it wasn't included in review
