### ISSUE TITLE
Error when running 'comp_bayes_lm' function

### ISSUE THREAD

**Issue by pvgansbe** [rudeboybert/forestecology#89]
I am currently working on a study in which we want to model individual tree growth based on the local neighbourhood in a tree diversity experiment called FORBIO (https://treedivbelgium.ugent.be/pl_forbio.html).

I succeeded in constructing a datafile that looks identical to the “focal_vs_comp_ex” datafile from the package. However, when I try to run the ‘comp_bayes_lm’ function, I get an error. 

Do you have any idea on how I could solve this issue? Is there still an issue in the architecture of my data frame?

Below a sample of my data (.rds in a zip file), the code I used and the error I received

Data: 
[sample_data.zip](https://github.com/rudeboybert/forestecology/files/11770517/sample_data.zip)

Code:
        comp_bayes_lm <- sample_data %>%
          comp_bayes_lm(prior_param = NULL, run_shuffle = FALSE)

Error: 
        Error in `summarise()`:
        i In argument: `geometry = .Primitive("sum")(geometry)`.
        i In group 1: `focal_ID = 1`, `comp_sp = "Acer"`.
        Caused by error:
        ! invalid 'type' (list) of argument
        Run `rlang::last_trace()` to see where the error occurred.

Thanks a lot!

**Comment by dallenmidd** [comment]
There are some differences in the structure between `sample_data` and `focal_vs_comp_ex` which I think give this error.
<img width="616" alt="Screen Shot 2023-06-19 at 10 35 13 AM" src="https://github.com/rudeboybert/forestecology/assets/20326594/7eed679e-545c-44c9-af91-31d16fe5d259">

I was able to do this code to line them up better (remove the spatial data, get the nesting structure to be the same, and change `comp_sp` to a factor):

```
sample_data2 <- sample_data %>%
  as_tibble() %>%
  unnest(cols = 'comp') %>%
  mutate(comp_sp = as.factor(comp_sp)) %>%
  nest(comp = c(comp_ID, dist, comp_sp, comp_x_var))
```

But then I get a different error when I try
```
comp_bayes_lm_ex <- test2 %>%
  comp_bayes_lm(prior_param = NULL)
```
The error is `Error in t(X) %*% y : non-conformable arguments`

Any idea @rudeboybert ?

**Comment by rudeboybert** [comment]
Hey all, thanks for catching that @dallenmidd. Indeed the `comp` variable needs to be a vector of lists, rather than a vector of lists of tibbles. I agree it's confusing, you can find more info on this topic [here](https://posit.co/resources/videos/how-to-work-with-list-columns/). If you're curious, we can take a look at the code/data that you used to create the `sample_data.Rds` from scratch to see what's going on. 

However the second error is due to 4 out of the 100 `sample_data$growth` values being `NA`; making those numerical corrects the error. 

Below is a combination of David and my code:
```
library(tidyverse)
library(forestecology)
sample_data <- readRDS("~/Downloads/sample_data")

# original error:
comp_bayes_lm <- sample_data %>%
  comp_bayes_lm(prior_param = NULL, run_shuffle = FALSE)

# As David pointed out, comp variable has to be a vector of lists
focal_vs_comp_ex

# original sample_data$comp is vector of lists of tibbles
sample_data

# corrected sample_data2$comp now has vector of lists
sample_data2 <- sample_data %>%
  as_tibble() %>%
  unnest(cols = 'comp') %>%
  mutate(comp_sp = as.factor(comp_sp)) %>%
  nest(comp = c(comp_ID, dist, comp_sp, comp_x_var))

# new error:
comp_bayes_lm_ex <- sample_data2 %>%
  comp_bayes_lm(prior_param = NULL)

# Four of the growth values are NA
sample_data$growth

# If we replace them with (made-up) numerical values, error disappears 
sample_data <- sample_data %>% 
  mutate(growth = ifelse(is.na(growth), 1, growth))

comp_bayes_lm_ex <- sample_data2 %>%
  comp_bayes_lm(prior_param = NULL)
```

**Comment by rudeboybert** [comment]
Let us know if you have any other issues @pvgansbe and thanks for using `forestecology`

**Comment by pvgansbe** [comment]
Hello @dallenmidd. and @rudeboybert ,

Thank you so much for the support and the quick follow-up. It was indeed the issue with the vector of tibles instead of a vector of lists that was causing the problem! 

Now everything seems to run smoothly. Thanks again!!
